{% set name = "pyjsparser" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyjsparser-{{ version }}.tar.gz
  sha256: be60da6b778cc5a5296a69d8e7d614f1f870faf94e1b1b6ac591f2ad5d729579

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyjsparser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PiotrDabkowski/pyjsparser
  summary: Fast javascript parser (based on esprima.js)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/PiotrDabkowski/pyjsparser
  dev_url: https://github.com/PiotrDabkowski/pyjsparser

extra:
  recipe-maintainers:
    - dschreij
    - smathot
    - xylar
